[Tue Dec 06 2016 11:33:14 GMT+0800 (CST)]/
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/Berger/code/node/bistu-data-mining-show/node_modules/mongodb-core/lib/topologies/server.js:309:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/Berger/code/node/bistu-data-mining-show/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/Berger/code/node/bistu-data-mining-show/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Tue Dec 06 2016 11:34:32 GMT+0800 (CST)]/
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
